version: "3.9"
services:
  flask_app:
    image: flask-app:v1
    build: .
    ports:
      - "80:8080"
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.1'
          memory: 128M
        limits:
          cpus: '1'
          memory: 512M